name: CI/CD Pipeline

on:
  push:
    branches: [main, master, develop]

jobs:
  build-backend:
    name: 🔧 Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t tp-backend ./backend

  build-frontend:
    name: 🎨 Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t tp-frontend ./frontend
