name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, master]
  pull_request:
    branches: [master]

jobs:
  build-docker:
    name: 🐳 Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build backend
        run: docker build -t tp-backend ./backend

      - name: Build frontend
        run: docker build -t tp-frontend ./frontend
